/* The following code was generated by JFlex 1.4.3 on 18/10/16 23:26 */

import java.util.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 18/10/16 23:26 from the specification file
 * <tt>LexicalAnalyzer.flex</tt>
 */
class LexicalAnalyzer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int CODE = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\12\0\1\26\2\0\1\25\22\0\1\40\1\27\6\0\1\33\1\34"+
    "\1\24\1\36\1\31\1\35\1\22\1\37\12\2\3\0\1\32\3\0"+
    "\1\13\1\1\1\30\1\15\1\6\1\16\1\7\1\17\1\3\2\1"+
    "\1\20\1\14\1\4\1\12\1\11\1\23\1\10\1\21\1\5\6\1"+
    "\6\0\1\13\1\1\1\30\1\15\1\6\1\16\1\7\1\17\1\3"+
    "\2\1\1\20\1\14\1\4\1\12\1\11\1\23\1\10\1\21\1\5"+
    "\6\1\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\6\2\1\1\1\4\1\1"+
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\7\16\1\2\1\17\5\2\1\20\10\0\1\17"+
    "\5\16\1\20\2\2\1\21\4\2\11\0\1\16\1\21"+
    "\4\16\1\2\1\22\2\2\1\23\3\2\1\24\1\0"+
    "\1\25\1\26\1\27\1\30\1\0\1\31\1\32\1\22"+
    "\2\16\1\23\3\16\1\2\1\33\1\34\1\35\2\2"+
    "\1\36\1\37\1\33\1\34\2\16\1\2\1\40\1\2"+
    "\1\16\1\41\2\42";

  private static int [] zzUnpackAction() {
    int [] result = new int[118];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\41\0\102\0\143\0\102\0\204\0\245\0\306"+
    "\0\347\0\u0108\0\u0129\0\u014a\0\102\0\u016b\0\u018c\0\102"+
    "\0\102\0\102\0\102\0\102\0\102\0\102\0\102\0\u01ad"+
    "\0\u01ce\0\u01ef\0\u0210\0\u0231\0\u0252\0\u0273\0\u0294\0\143"+
    "\0\u02b5\0\u02d6\0\u02f7\0\u0318\0\u0339\0\143\0\u035a\0\u037b"+
    "\0\u039c\0\u03bd\0\u03de\0\u03ff\0\u0420\0\u016b\0\u01ad\0\u0441"+
    "\0\u0462\0\u0483\0\u04a4\0\u04c5\0\u01ad\0\u04e6\0\u0507\0\u0528"+
    "\0\u0549\0\u056a\0\u058b\0\u05ac\0\u05cd\0\u05ee\0\u060f\0\u0630"+
    "\0\u0651\0\u0672\0\u0693\0\u06b4\0\u06d5\0\u06f6\0\u0717\0\u0738"+
    "\0\u0759\0\u077a\0\u079b\0\u07bc\0\143\0\u07dd\0\u07fe\0\143"+
    "\0\u081f\0\u0840\0\u0861\0\102\0\u0882\0\102\0\102\0\102"+
    "\0\102\0\u08a3\0\102\0\102\0\u01ad\0\u08c4\0\u08e5\0\u01ad"+
    "\0\u0906\0\u0927\0\u0948\0\u0969\0\143\0\143\0\102\0\u098a"+
    "\0\u09ab\0\102\0\102\0\u01ad\0\u01ad\0\u09cc\0\u09ed\0\u0a0e"+
    "\0\102\0\u0a2f\0\u0a50\0\143\0\143\0\u01ad";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[118];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\4\1\7\1\10\1\4"+
    "\1\11\1\12\3\4\1\13\4\4\1\14\1\4\1\15"+
    "\1\16\1\17\1\3\1\4\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\3\1\30\1\5\1\31"+
    "\1\30\1\32\1\33\1\30\1\34\1\35\3\30\1\36"+
    "\4\30\1\14\1\30\1\15\1\16\1\17\1\3\1\30"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\42\0\21\4\1\0\1\4\4\0\1\4\11\0\3\4"+
    "\1\37\11\4\1\40\3\4\1\0\1\4\4\0\1\4"+
    "\11\0\16\4\1\41\2\4\1\0\1\4\4\0\1\4"+
    "\11\0\3\4\1\42\13\4\1\43\1\4\1\0\1\4"+
    "\4\0\1\4\11\0\5\4\1\44\13\4\1\0\1\4"+
    "\4\0\1\4\11\0\7\4\1\45\11\4\1\0\1\4"+
    "\4\0\1\4\11\0\11\4\1\46\7\4\1\0\1\4"+
    "\4\0\1\4\14\0\1\47\1\0\1\50\1\51\2\0"+
    "\1\52\1\53\4\0\1\54\46\0\1\17\27\0\1\55"+
    "\6\0\1\55\1\56\1\17\2\55\11\0\21\30\1\0"+
    "\1\30\4\0\1\30\11\0\15\30\1\57\3\30\1\0"+
    "\1\30\4\0\1\30\11\0\16\30\1\60\2\30\1\0"+
    "\1\30\4\0\1\30\11\0\3\30\1\61\13\30\1\62"+
    "\1\30\1\0\1\30\4\0\1\30\11\0\5\30\1\63"+
    "\13\30\1\0\1\30\4\0\1\30\11\0\7\30\1\64"+
    "\11\30\1\0\1\30\4\0\1\30\11\0\11\30\1\65"+
    "\7\30\1\0\1\30\4\0\1\30\11\0\4\4\1\66"+
    "\14\4\1\0\1\4\4\0\1\4\11\0\5\4\1\67"+
    "\13\4\1\0\1\4\4\0\1\4\11\0\14\4\1\70"+
    "\4\4\1\0\1\4\4\0\1\4\11\0\20\4\1\71"+
    "\1\0\1\4\4\0\1\4\11\0\12\4\1\72\6\4"+
    "\1\0\1\4\4\0\1\4\11\0\2\4\1\73\6\4"+
    "\1\74\7\4\1\0\1\4\4\0\1\4\16\0\1\75"+
    "\3\0\1\76\51\0\1\77\22\0\1\100\1\101\42\0"+
    "\1\102\34\0\1\103\41\0\1\104\1\105\32\0\26\55"+
    "\1\17\12\55\1\0\5\30\1\106\13\30\1\0\1\30"+
    "\4\0\1\30\11\0\14\30\1\107\4\30\1\0\1\30"+
    "\4\0\1\30\11\0\20\30\1\110\1\0\1\30\4\0"+
    "\1\30\11\0\12\30\1\111\6\30\1\0\1\30\4\0"+
    "\1\30\11\0\2\30\1\112\6\30\1\113\7\30\1\0"+
    "\1\30\4\0\1\30\11\0\5\4\1\114\13\4\1\0"+
    "\1\4\4\0\1\4\11\0\3\4\1\115\15\4\1\0"+
    "\1\4\4\0\1\4\11\0\2\4\1\116\11\4\1\117"+
    "\4\4\1\0\1\4\4\0\1\4\11\0\5\4\1\120"+
    "\13\4\1\0\1\4\4\0\1\4\11\0\14\4\1\121"+
    "\4\4\1\0\1\4\4\0\1\4\11\0\3\4\1\122"+
    "\15\4\1\0\1\4\4\0\1\4\11\0\6\4\1\123"+
    "\12\4\1\0\1\4\4\0\1\4\32\0\1\124\23\0"+
    "\1\125\55\0\1\126\40\0\1\127\40\0\1\130\40\0"+
    "\1\131\33\0\1\132\45\0\1\133\40\0\1\134\17\0"+
    "\3\30\1\135\15\30\1\0\1\30\4\0\1\30\11\0"+
    "\2\30\1\136\11\30\1\137\4\30\1\0\1\30\4\0"+
    "\1\30\11\0\5\30\1\140\13\30\1\0\1\30\4\0"+
    "\1\30\11\0\14\30\1\141\4\30\1\0\1\30\4\0"+
    "\1\30\11\0\3\30\1\142\15\30\1\0\1\30\4\0"+
    "\1\30\11\0\6\30\1\143\12\30\1\0\1\30\4\0"+
    "\1\30\11\0\6\4\1\144\12\4\1\0\1\4\4\0"+
    "\1\4\11\0\15\4\1\145\3\4\1\0\1\4\4\0"+
    "\1\4\11\0\11\4\1\146\7\4\1\0\1\4\4\0"+
    "\1\4\11\0\21\4\1\0\1\4\1\147\3\0\1\4"+
    "\11\0\4\4\1\150\14\4\1\0\1\4\4\0\1\4"+
    "\11\0\7\4\1\151\11\4\1\0\1\4\4\0\1\4"+
    "\32\0\1\152\40\0\1\153\17\0\15\30\1\154\3\30"+
    "\1\0\1\30\4\0\1\30\11\0\11\30\1\155\7\30"+
    "\1\0\1\30\4\0\1\30\11\0\21\30\1\0\1\30"+
    "\1\147\3\0\1\30\11\0\4\30\1\156\14\30\1\0"+
    "\1\30\4\0\1\30\11\0\7\30\1\157\11\30\1\0"+
    "\1\30\4\0\1\30\11\0\5\4\1\160\13\4\1\0"+
    "\1\4\4\0\1\4\11\0\21\4\1\0\1\4\1\161"+
    "\3\0\1\4\11\0\12\4\1\162\6\4\1\0\1\4"+
    "\4\0\1\4\11\0\21\30\1\0\1\30\1\161\3\0"+
    "\1\30\11\0\12\30\1\163\6\30\1\0\1\30\4\0"+
    "\1\30\11\0\7\4\1\164\11\4\1\0\1\4\4\0"+
    "\1\4\11\0\13\4\1\165\5\4\1\0\1\4\4\0"+
    "\1\4\11\0\13\30\1\166\5\30\1\0\1\30\4\0"+
    "\1\30\10\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2673];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\7\1\1\11\2\1\10\11"+
    "\17\1\10\0\16\1\11\0\16\1\1\11\1\0\4\11"+
    "\1\0\2\11\12\1\1\11\2\1\2\11\5\1\1\11"+
    "\5\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[118];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

    private ArrayList<Symbol> symbolTable = new ArrayList<Symbol>();

    private Symbol symbol(LexicalUnit type, Object value) {
        Symbol sb = new Symbol(type, yyline, yycolumn, value);
        System.out.println(sb.toString());
        return sb;
    }

    //add an identifier in the symbolTable if not in the table
    private void addInTable(Symbol sb) {
        boolean inTable = false;
        for (Symbol symb : symbolTable) {
            if (sb.getValue().equals(symb.getValue())) {
                inTable = true;
            }
        }
        if (!inTable) {
            symbolTable.add(sb);
        }
    }

    //print all the identifiers with the line where first occuring
    private void printSymbolTable() {
        System.out.println("Identifiers");
        for (Symbol symb : symbolTable) {
            System.out.println(symb.getValue() + "\t" + symb.getLine());
        }
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexicalAnalyzer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  LexicalAnalyzer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 124) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
        printSymbolTable();

    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 27: 
          { Symbol symb = symbol(LexicalUnit.ENDIF, yytext());
          }
        case 35: break;
        case 24: 
          { Symbol symb = symbol(LexicalUnit.OR, yytext());
          }
        case 36: break;
        case 12: 
          { Symbol symb = symbol(LexicalUnit.DIVIDE, yytext());
          }
        case 37: break;
        case 20: 
          { Symbol symb = symbol(LexicalUnit.DIFFERENT, yytext());
          }
        case 38: break;
        case 23: 
          { Symbol symb = symbol(LexicalUnit.GREATER_EQUAL, yytext());
          }
        case 39: break;
        case 28: 
          { Symbol symb = symbol(LexicalUnit.ENDDO, yytext());
          }
        case 40: break;
        case 26: 
          { Symbol symb = symbol(LexicalUnit.SMALLER_EQUAL, yytext());
          }
        case 41: break;
        case 9: 
          { Symbol symb = symbol(LexicalUnit.RIGHT_PARENTHESIS, yytext());
          }
        case 42: break;
        case 4: 
          { Symbol symb = symbol(LexicalUnit.TIMES, yytext());
          }
        case 43: break;
        case 25: 
          { Symbol symb = symbol(LexicalUnit.SMALLER, yytext());
          }
        case 44: break;
        case 18: 
          { Symbol symb = symbol(LexicalUnit.THEN, yytext());
          }
        case 45: break;
        case 19: 
          { Symbol symb = symbol(LexicalUnit.ELSE, yytext());
          }
        case 46: break;
        case 8: 
          { Symbol symb = symbol(LexicalUnit.LEFT_PARENTHESIS, yytext());
          }
        case 47: break;
        case 33: 
          { Symbol symb = symbol(LexicalUnit.INTEGER, yytext());
                yybegin(CODE);
          }
        case 48: break;
        case 21: 
          { Symbol symb = symbol(LexicalUnit.EQUAL_COMPARE, yytext());
          }
        case 49: break;
        case 17: 
          { Symbol symb = symbol(LexicalUnit.END, yytext());
          }
        case 50: break;
        case 14: 
          { Symbol symb = symbol(LexicalUnit.VARNAME, yytext());
        addInTable(symb);
          }
        case 51: break;
        case 15: 
          { Symbol symb = symbol(LexicalUnit.IF, yytext());
          }
        case 52: break;
        case 32: 
          { Symbol symb = symbol(LexicalUnit.PRINT, yytext());
          }
        case 53: break;
        case 16: 
          { Symbol symb = symbol(LexicalUnit.DO, yytext());
          }
        case 54: break;
        case 34: 
          { Symbol symb = symbol(LexicalUnit.PROGRAM, yytext());
          }
        case 55: break;
        case 7: 
          { Symbol symb = symbol(LexicalUnit.EQUAL, yytext());
          }
        case 56: break;
        case 2: 
          { Symbol symb = symbol(LexicalUnit.VARNAME, yytext());
          }
        case 57: break;
        case 29: 
          { Symbol symb = symbol(LexicalUnit.READ, yytext());
          }
        case 58: break;
        case 31: 
          { Symbol symb = symbol(LexicalUnit.AND, yytext());
          }
        case 59: break;
        case 11: 
          { Symbol symb = symbol(LexicalUnit.PLUS, yytext());
          }
        case 60: break;
        case 22: 
          { Symbol symb = symbol(LexicalUnit.GREATER, yytext());
          }
        case 61: break;
        case 1: 
          { System.out.println("ERROR");
          }
        case 62: break;
        case 6: 
          { Symbol symb = symbol(LexicalUnit.COMMA, yytext());
          }
        case 63: break;
        case 30: 
          { Symbol symb = symbol(LexicalUnit.NOT, yytext());
          }
        case 64: break;
        case 3: 
          { Symbol symb = symbol(LexicalUnit.NUMBER, yytext());
          }
        case 65: break;
        case 5: 
          { Symbol symb = symbol(LexicalUnit.ENDLINE, "\t");
          }
        case 66: break;
        case 10: 
          { Symbol symb = symbol(LexicalUnit.MINUS, yytext());
          }
        case 67: break;
        case 13: 
          { 
          }
        case 68: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return YYEOF;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java LexicalAnalyzer <inputfile>");
    }
    else {
      for (int i = 0; i < argv.length; i++) {
        LexicalAnalyzer scanner = null;
        try {
          scanner = new LexicalAnalyzer( new java.io.FileReader(argv[i]) );
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
